### ISSUE TITLE
Hanging solver due to buffer not read

### ISSUE THREAD

**Issue by rtaupe** [DeMaCS-UNICAL/EmbASP-Java#9]
The existing implementation causes clingo to hang when run on Windows and when clingo's output exceeds some
buffer size.

From https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html:

> Because some native platforms only provide limited buffer size for standard input and output streams, failure to promptly write the input stream or read the output stream of the subprocess may cause the subprocess to block, or even deadlock.

**Comment by stefanogermano** [comment]
Thank you for letting us know this and for solving it in your pull request.

We really appreciate your contribution.
